
const ActionTypes = {
    LOAD_CONVERSATION_REQUEST: 'LOAD_CONVERSATION_REQUEST',
    LOAD_CONVERSATION_FAIL: 'LOAD_CONVERSATION_FAIL',
    LOAD_CONVERSATION_SUCCESS: 'LOAD_CONVERSATION_SUCCESS',

    CHANGE_MESSAGE_TEXT: 'CHANGE_MESSAGE_TEXT', 

    CHANGE_CONVERSATION_TEXT: 'CHANGE_CONVERSATION_TEXT', 

    SEND_MESSAGE_REQUEST: 'SEND_MESSAGE_REQUEST',
    SEND_MESSAGE_FAIL: 'SEND_MESSAGE_FAIL',
    SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',

    ADD_PARTICIPANT_REQUEST: 'ADD_PARTICIPANT_REQUEST',
    ADD_PARTICIPANT_FAIL: 'ADD_PARTICIPANT_FAIL',
    ADD_PARTICIPANT_SUCCESS: 'ADD_PARTICIPANT_SUCCESS',


    CHANGE_TERMINAL_INPUT_TEXT: 'CHANGE_TERMINAL_INPUT_TEXT',
    SUBMIT_TERMINAL_INPUT_TEXT_REQUEST: 'SUBMIT_TERMINAL_INPUT_TEXT_REQUEST',
    SUBMIT_TERMINAL_INPUT_TEXT_FAIL: 'SUBMIT_TERMINAL_INPUT_TEXT_FAIL',
    SUBMIT_TERMINAL_INPUT_TEXT_SUCCESS: 'SUBMIT_TERMINAL_INPUT_TEXT_SUCCESS',

    CREATE_BRANCH_REQUEST: 'CREATE_BRANCH_REQUEST_REQUEST',
    CREATE_BRANCH_FAIL: 'CREATE_BRANCH_REQUEST_FAIL',
    CREATE_BRANCH_SUCCESS: 'CREATE_BRANCH_REQUEST_SUCCESS',

    CHECKOUT_BRANCH_REQUEST: 'CHECKOUT_BRANCH_REQUEST',
    CHECKOUT_BRANCH_FAIL: 'CHECKOUT_BRANCH_FAIL',
    CHECKOUT_BRANCH_SUCCESS: 'CHECKOUT_BRANCH_SUCCESS',

    DELETE_BRANCH_REQUEST: 'DELETE_BRANCH_REQUEST',
    DELETE_BRANCH_FAIL: 'DELETE_BRANCH_FAIL',
    DELETE_BRANCH_SUCCESS: 'DELETE_BRANCH_SUCCESS',


    ADD_CONVERSATION_REQUEST: 'ADD_CONVERSATION_REQUEST',
    ADD_CONVERSATION_FAIL: 'ADD_CONVERSATION_FAIL',
    ADD_CONVERSATION_SUCCESS: 'ADD_CONVERSATION_SUCCESS',

    CHECKOUT_CONVERSATION_REQUEST: 'CHECKOUT_CONVERSATION_REQUEST',
    CHECKOUT_CONVERSATION_FAIL: 'CHECKOUT_CONVERSATION_FAIL',
    CHECKOUT_CONVERSATION_SUCCESS: 'CHECKOUT_CONVERSATION_SUCCESS',

    DELETE_CONVERSATION_REQUEST: 'DELETE_CONVERSATION_REQUEST',
    DELETE_CONVERSATION_FAIL: 'DELETE_CONVERSATION_FAIL',
    DELETE_CONVERSATION_SUCCESS: 'DELETE_CONVERSATION_SUCCESS',
};

export default ActionTypes;
