
const ActionTypes = {
    LOAD_CONVERSATION: 'LOAD_CONVERSATION',
    CHANGE_MESSAGE_TEXT: 'CHANGE_MESSAGE_TEXT', 
    CHANGE_CONVERSATION_TEXT: 'CHANGE_CONVERSATION_TEXT', 
    SEND_MESSAGE: 'SEND_MESSAGE',
    ADD_PARTICIPANT: 'ADD_PARTICIPANT',

    CHANGE_TERMINAL_INPUT_TEXT: 'CHANGE_TERMINAL_INPUT_TEXT',
    SUBMIT_TERMINAL_INPUT_TEXT: 'SUBMIT_TERMINAL_INPUT_TEXT',

    CREATE_BRANCH: 'CREATE_BRANCH',
    CHECKOUT_BRANCH: 'CHECKOUT_BRANCH',
    DELETE_BRANCH: 'DELETE_BRANCH',

    CREATE_CONVERSATION: 'CREATE_CONVERSATION',
    CHECKOUT_CONVERSATION: 'CHECKOUT_CONVERSATION',
    DELETE_CONVERSATION: 'DELETE_CONVERSATION',
};

export default ActionTypes;
